name: Turbo changed projects
description: Detect which turbo projects has changes
inputs:
  github_event:
    description: Github event variable github.event
    required: true
outputs:
  changedProjects:
    description: List of changed project.
runs:
  using: node16
  main: dist/index.js
