name: Turbo changed projects
description: Detect which turbo projects has changes
inputs:
  githubEvent:
    description: Github event variable ${{ github.event }}
    required: true
outputs:
  changedProjects:
    description: List of changed project.
runs:
  using: node16
  main: dist/index.js
